// All IANA timezones grouped by country.
//
// Source: the tzdb `zone1970.tab` country->zone mapping plus ISO-3166 country
// names. Data is static so it works in every browser regardless of
// `Intl.supportedValuesOf` support. `config.timezone` on the clock widget stays
// a raw IANA string (e.g. "America/New_York"), so the stored shape and the
// Flutter renderer contract are unchanged — this file only drives the picker UI.

export interface TzEntry {
  /** IANA zone id, e.g. "America/New_York". */
  tz: string;
  /** Human label derived from the zone id, e.g. "New York". */
  city: string;
}

export interface TzCountryGroup {
  country: string;
  zones: TzEntry[];
}

const COUNTRY_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AL: "Albania",
  AM: "Armenia",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "Samoa (American)",
  AT: "Austria",
  AU: "Australia",
  AZ: "Azerbaijan",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BG: "Bulgaria",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ES: "Spain",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GB: "United Kingdom",
  GE: "Georgia",
  GF: "French Guiana",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GR: "Greece",
  GS: "South Georgia & the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HN: "Honduras",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KP: "North Korea",
  KR: "South Korea",
  KZ: "Kazakhstan",
  LB: "Lebanon",
  LK: "Sri Lanka",
  LR: "Liberia",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  MH: "Marshall Islands",
  MM: "Myanmar (Burma)",
  MN: "Mongolia",
  MO: "Macau",
  MQ: "Martinique",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "St Pierre & Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome & Principe",
  SV: "El Salvador",
  SY: "Syria",
  TC: "Turks & Caicos Is",
  TD: "Chad",
  TF: "French Southern & Antarctic Lands",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "East Timor",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UM: "US minor outlying islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VE: "Venezuela",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa (western)",
  YE: "Yemen",
  ZA: "South Africa",
  ZW: "Zimbabwe",
};

// Country code -> IANA zones (from tzdb zone1970.tab; canonical zones only).
const ZONES_BY_COUNTRY: Record<string, string[]> = {
  AD: ["Europe/Andorra"],
  AE: ["Asia/Dubai"],
  AF: ["Asia/Kabul"],
  AL: ["Europe/Tirane"],
  AM: ["Asia/Yerevan"],
  AQ: [
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/Mawson",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Antarctica/DumontDUrville",
    "Antarctica/Syowa",
    "Antarctica/McMurdo",
  ],
  AR: [
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Cordoba",
    "America/Argentina/Salta",
    "America/Argentina/Jujuy",
    "America/Argentina/Tucuman",
    "America/Argentina/Catamarca",
    "America/Argentina/La_Rioja",
    "America/Argentina/San_Juan",
    "America/Argentina/Mendoza",
    "America/Argentina/San_Luis",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Ushuaia",
  ],
  AS: ["Pacific/Pago_Pago"],
  AT: ["Europe/Vienna"],
  AU: [
    "Australia/Lord_Howe",
    "Antarctica/Macquarie",
    "Australia/Hobart",
    "Australia/Melbourne",
    "Australia/Sydney",
    "Australia/Broken_Hill",
    "Australia/Brisbane",
    "Australia/Lindeman",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Australia/Perth",
    "Australia/Eucla",
  ],
  AZ: ["Asia/Baku"],
  BB: ["America/Barbados"],
  BD: ["Asia/Dhaka"],
  BE: ["Europe/Brussels"],
  BG: ["Europe/Sofia"],
  BM: ["Atlantic/Bermuda"],
  BN: ["Asia/Brunei"],
  BO: ["America/La_Paz"],
  BR: [
    "America/Noronha",
    "America/Belem",
    "America/Fortaleza",
    "America/Recife",
    "America/Araguaina",
    "America/Maceio",
    "America/Bahia",
    "America/Sao_Paulo",
    "America/Campo_Grande",
    "America/Cuiaba",
    "America/Santarem",
    "America/Porto_Velho",
    "America/Boa_Vista",
    "America/Manaus",
    "America/Eirunepe",
    "America/Rio_Branco",
  ],
  BS: ["America/Nassau"],
  BT: ["Asia/Thimphu"],
  BY: ["Europe/Minsk"],
  BZ: ["America/Belize"],
  CA: [
    "America/St_Johns",
    "America/Halifax",
    "America/Glace_Bay",
    "America/Moncton",
    "America/Goose_Bay",
    "America/Toronto",
    "America/Iqaluit",
    "America/Winnipeg",
    "America/Resolute",
    "America/Rankin_Inlet",
    "America/Regina",
    "America/Swift_Current",
    "America/Edmonton",
    "America/Cambridge_Bay",
    "America/Inuvik",
    "America/Dawson_Creek",
    "America/Fort_Nelson",
    "America/Whitehorse",
    "America/Dawson",
    "America/Vancouver",
  ],
  CH: ["Europe/Zurich"],
  CI: ["Africa/Abidjan"],
  CK: ["Pacific/Rarotonga"],
  CL: ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"],
  CN: ["Asia/Shanghai", "Asia/Urumqi"],
  CO: ["America/Bogota"],
  CR: ["America/Costa_Rica"],
  CU: ["America/Havana"],
  CV: ["Atlantic/Cape_Verde"],
  CW: ["America/Curacao"],
  CY: ["Asia/Nicosia", "Asia/Famagusta"],
  CZ: ["Europe/Prague"],
  DE: ["Europe/Berlin", "Europe/Busingen"],
  DK: ["Europe/Copenhagen"],
  DO: ["America/Santo_Domingo"],
  DZ: ["Africa/Algiers"],
  EC: ["America/Guayaquil", "Pacific/Galapagos"],
  EE: ["Europe/Tallinn"],
  EG: ["Africa/Cairo"],
  EH: ["Africa/El_Aaiun"],
  ES: ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"],
  FI: ["Europe/Helsinki"],
  FJ: ["Pacific/Fiji"],
  FK: ["Atlantic/Stanley"],
  FM: ["Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"],
  FO: ["Atlantic/Faroe"],
  FR: ["Europe/Paris"],
  GB: ["Europe/London"],
  GE: ["Asia/Tbilisi"],
  GF: ["America/Cayenne"],
  GH: ["Africa/Accra"],
  GI: ["Europe/Gibraltar"],
  GL: [
    "America/Nuuk",
    "America/Danmarkshavn",
    "America/Scoresbysund",
    "America/Thule",
  ],
  GR: ["Europe/Athens"],
  GS: ["Atlantic/South_Georgia"],
  GT: ["America/Guatemala"],
  GU: ["Pacific/Guam"],
  GW: ["Africa/Bissau"],
  GY: ["America/Guyana"],
  HK: ["Asia/Hong_Kong"],
  HN: ["America/Tegucigalpa"],
  HT: ["America/Port-au-Prince"],
  HU: ["Europe/Budapest"],
  ID: ["Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"],
  IE: ["Europe/Dublin"],
  IL: ["Asia/Jerusalem"],
  IN: ["Asia/Kolkata"],
  IO: ["Indian/Chagos"],
  IQ: ["Asia/Baghdad"],
  IR: ["Asia/Tehran"],
  IS: ["Atlantic/Reykjavik"],
  IT: ["Europe/Rome"],
  JM: ["America/Jamaica"],
  JO: ["Asia/Amman"],
  JP: ["Asia/Tokyo"],
  KE: ["Africa/Nairobi"],
  KG: ["Asia/Bishkek"],
  KH: ["Asia/Phnom_Penh"],
  KI: ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"],
  KP: ["Asia/Pyongyang"],
  KR: ["Asia/Seoul"],
  KZ: [
    "Asia/Almaty",
    "Asia/Qyzylorda",
    "Asia/Qostanay",
    "Asia/Aqtobe",
    "Asia/Aqtau",
    "Asia/Atyrau",
    "Asia/Oral",
  ],
  LB: ["Asia/Beirut"],
  LK: ["Asia/Colombo"],
  LR: ["Africa/Monrovia"],
  LT: ["Europe/Vilnius"],
  LU: ["Europe/Luxembourg"],
  LV: ["Europe/Riga"],
  LY: ["Africa/Tripoli"],
  MA: ["Africa/Casablanca"],
  MC: ["Europe/Monaco"],
  MD: ["Europe/Chisinau"],
  MH: ["Pacific/Majuro", "Pacific/Kwajalein"],
  MM: ["Asia/Yangon"],
  MN: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  MO: ["Asia/Macau"],
  MQ: ["America/Martinique"],
  MT: ["Europe/Malta"],
  MU: ["Indian/Mauritius"],
  MV: ["Indian/Maldives"],
  MX: [
    "America/Mexico_City",
    "America/Cancun",
    "America/Merida",
    "America/Monterrey",
    "America/Matamoros",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Ojinaga",
    "America/Mazatlan",
    "America/Bahia_Banderas",
    "America/Hermosillo",
    "America/Tijuana",
  ],
  MY: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  MZ: ["Africa/Maputo"],
  NA: ["Africa/Windhoek"],
  NC: ["Pacific/Noumea"],
  NF: ["Pacific/Norfolk"],
  NG: ["Africa/Lagos"],
  NI: ["America/Managua"],
  NL: ["Europe/Amsterdam"],
  NO: ["Europe/Oslo"],
  NP: ["Asia/Kathmandu"],
  NR: ["Pacific/Nauru"],
  NU: ["Pacific/Niue"],
  NZ: ["Pacific/Auckland", "Pacific/Chatham"],
  PA: ["America/Panama"],
  PE: ["America/Lima"],
  PF: ["Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"],
  PG: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  PH: ["Asia/Manila"],
  PK: ["Asia/Karachi"],
  PL: ["Europe/Warsaw"],
  PM: ["America/Miquelon"],
  PN: ["Pacific/Pitcairn"],
  PR: ["America/Puerto_Rico"],
  PS: ["Asia/Gaza", "Asia/Hebron"],
  PT: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  PW: ["Pacific/Palau"],
  PY: ["America/Asuncion"],
  QA: ["Asia/Qatar"],
  RE: ["Indian/Reunion"],
  RO: ["Europe/Bucharest"],
  RS: ["Europe/Belgrade"],
  RU: [
    "Europe/Kaliningrad",
    "Europe/Moscow",
    "Europe/Simferopol",
    "Europe/Kirov",
    "Europe/Volgograd",
    "Europe/Astrakhan",
    "Europe/Saratov",
    "Europe/Ulyanovsk",
    "Europe/Samara",
    "Asia/Yekaterinburg",
    "Asia/Omsk",
    "Asia/Novosibirsk",
    "Asia/Barnaul",
    "Asia/Tomsk",
    "Asia/Novokuznetsk",
    "Asia/Krasnoyarsk",
    "Asia/Irkutsk",
    "Asia/Chita",
    "Asia/Yakutsk",
    "Asia/Khandyga",
    "Asia/Vladivostok",
    "Asia/Ust-Nera",
    "Asia/Magadan",
    "Asia/Sakhalin",
    "Asia/Srednekolymsk",
    "Asia/Kamchatka",
    "Asia/Anadyr",
  ],
  SA: ["Asia/Riyadh"],
  SB: ["Pacific/Guadalcanal"],
  SC: ["Indian/Mahe"],
  SD: ["Africa/Khartoum"],
  SE: ["Europe/Stockholm"],
  SG: ["Asia/Singapore"],
  SR: ["America/Paramaribo"],
  SS: ["Africa/Juba"],
  ST: ["Africa/Sao_Tome"],
  SV: ["America/El_Salvador"],
  SY: ["Asia/Damascus"],
  TC: ["America/Grand_Turk"],
  TD: ["Africa/Ndjamena"],
  TF: ["Indian/Kerguelen"],
  TH: ["Asia/Bangkok"],
  TJ: ["Asia/Dushanbe"],
  TK: ["Pacific/Fakaofo"],
  TL: ["Asia/Dili"],
  TM: ["Asia/Ashgabat"],
  TN: ["Africa/Tunis"],
  TO: ["Pacific/Tongatapu"],
  TR: ["Europe/Istanbul"],
  TT: ["America/Port_of_Spain"],
  TV: ["Pacific/Funafuti"],
  TW: ["Asia/Taipei"],
  TZ: ["Africa/Dar_es_Salaam"],
  UA: ["Europe/Kyiv"],
  UM: ["Pacific/Midway", "Pacific/Wake"],
  US: [
    "America/New_York",
    "America/Detroit",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/Indiana/Indianapolis",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Vevay",
    "America/Chicago",
    "America/Indiana/Tell_City",
    "America/Indiana/Knox",
    "America/Menominee",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/North_Dakota/Beulah",
    "America/Denver",
    "America/Boise",
    "America/Phoenix",
    "America/Los_Angeles",
    "America/Anchorage",
    "America/Juneau",
    "America/Sitka",
    "America/Metlakatla",
    "America/Yakutat",
    "America/Nome",
    "America/Adak",
    "Pacific/Honolulu",
  ],
  UY: ["America/Montevideo"],
  UZ: ["Asia/Samarkand", "Asia/Tashkent"],
  VE: ["America/Caracas"],
  VN: ["Asia/Ho_Chi_Minh"],
  VU: ["Pacific/Efate"],
  WF: ["Pacific/Wallis"],
  WS: ["Pacific/Apia"],
  YE: ["Asia/Aden"],
  ZA: ["Africa/Johannesburg"],
  ZW: ["Africa/Harare"],
};

function cityFromZone(tz: string): string {
  const segments = tz.split("/");
  return segments[segments.length - 1].replace(/_/g, " ");
}

export const TIMEZONE_GROUPS: TzCountryGroup[] = (() => {
  const groups: TzCountryGroup[] = [
    { country: "UTC", zones: [{ tz: "UTC", city: "UTC" }] },
  ];

  Object.keys(ZONES_BY_COUNTRY)
    .map((code) => ({
      code,
      name: COUNTRY_NAMES[code] ?? code,
    }))
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach(({ code, name }) => {
      const zones = ZONES_BY_COUNTRY[code]
        .map((tz) => ({ tz, city: cityFromZone(tz) }))
        .sort((a, b) => a.city.localeCompare(b.city));
      groups.push({ country: name, zones });
    });

  return groups;
})();
